// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ_KtQIUmIlKIblq2AxMiHs5XVqooJZwc',
    appId: '1:892497788889:web:3800bca030d4fe816463c8',
    messagingSenderId: '892497788889',
    projectId: 'contact-clone-c5e44',
    authDomain: 'contact-clone-c5e44.firebaseapp.com',
    storageBucket: 'contact-clone-c5e44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMjKGd2TA42-_mJ_JY0ibhU-r-IjKx4g',
    appId: '1:892497788889:android:2093195745beb38f6463c8',
    messagingSenderId: '892497788889',
    projectId: 'contact-clone-c5e44',
    storageBucket: 'contact-clone-c5e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yclHHJ6HK5-kOZraqoiTlaZ2vA33uvY',
    appId: '1:892497788889:ios:d3ad4c50db9ba9cf6463c8',
    messagingSenderId: '892497788889',
    projectId: 'contact-clone-c5e44',
    storageBucket: 'contact-clone-c5e44.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0yclHHJ6HK5-kOZraqoiTlaZ2vA33uvY',
    appId: '1:892497788889:ios:d3ad4c50db9ba9cf6463c8',
    messagingSenderId: '892497788889',
    projectId: 'contact-clone-c5e44',
    storageBucket: 'contact-clone-c5e44.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ_KtQIUmIlKIblq2AxMiHs5XVqooJZwc',
    appId: '1:892497788889:web:5967cd743486f73f6463c8',
    messagingSenderId: '892497788889',
    projectId: 'contact-clone-c5e44',
    authDomain: 'contact-clone-c5e44.firebaseapp.com',
    storageBucket: 'contact-clone-c5e44.firebasestorage.app',
  );
}
